version: '3.8'

services:

    fers-bff:
        image: fers-bff:latest
        hostname: fers-bff
        container_name: fers-bff
        restart: always
        ports:
            - 8080:8080
        environment:
            - FILE_STORAGE_DIR=\temp\demo
